# Generated by Django 5.2 on 2025-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
