# Generated by Django 5.2 on 2025-05-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_alter_userprofile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fullname',
        ),
    ]
