# Generated by Django 5.2.3 on 2025-07-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_userprofile_created_at_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('customer', 'Customer')], null=True),
        ),
    ]
