# Generated by Django 5.2.3 on 2025-07-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0006_alter_userprofile_description_alter_userprofile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/'),
        ),
    ]
