# Generated by Django 5.2 on 2025-08-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0007_alter_userprofile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='working_hours',
        ),
    ]
