# Generated by Django 5.2 on 2025-08-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0009_userprofile_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activation_token',
        ),
    ]
