# Generated by Django 5.2 on 2025-08-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0010_remove_userprofile_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_token',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
