# Generated by Django 5.2.3 on 2025-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0004_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
    ]
