# Generated by Django 5.2 on 2025-08-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/videos/original/'),
        ),
    ]
