# Generated by Django 5.2 on 2025-08-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0006_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/videos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
