# Generated by Django 5.2 on 2025-08-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0007_fileupload_category_fileupload_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='thumbnail',
        ),
    ]
