# Generated by Django 5.2 on 2025-08-18 17:13

import video_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=video_app.utils.thumbnail_upload_to)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/videos/original/')),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('m3u8_480p', models.FileField(blank=True, null=True, upload_to=video_app.utils.hls_480p_upload_to)),
                ('m3u8_720p', models.FileField(blank=True, null=True, upload_to=video_app.utils.hls_720p_upload_to)),
                ('m3u8_1080p', models.FileField(blank=True, null=True, upload_to=video_app.utils.hls_1080p_upload_to)),
            ],
        ),
    ]
