# Generated by Django 5.2 on 2025-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='m3u8_1080p',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/hls/1080p/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='m3u8_480p',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/hls/480p/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='m3u8_720p',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/hls/720p/'),
        ),
    ]
