# Generated by Django 5.2 on 2025-08-17 14:12

import video_app.tasks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_remove_video_thumbnail_url_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='m3u8_1080p',
            field=models.FileField(blank=True, null=True, upload_to=video_app.tasks.hls_1080p_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='m3u8_480p',
            field=models.FileField(blank=True, null=True, upload_to=video_app.tasks.hls_480p_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='m3u8_720p',
            field=models.FileField(blank=True, null=True, upload_to=video_app.tasks.hls_720p_upload_to),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=video_app.tasks.thumbnail_upload_to),
        ),
    ]
